builders:
  mapper:
    import: "package:smartstruct_generator/builder.dart"
    builder_factories: ["smartstructBuilder"]
    build_extensions: { ".dart": ["mapper.g.dart"] }
    auto_apply: dependents
    build_to: source
    # applies_builders: ["source_gen|combining_builder"]
    runs_before: ["injectable_generator|injectable_builder"]
    required_inputs: [".g.dart"]
